### ISSUE TITLE
add a notification on laboite.cc to redirect new users to lenuage.io

### ISSUE THREAD

**Issue by jlebunetel** [laboiteproject/docs#2]
It would be interesting to inform new users who have stumbled upon the laboite.cc website by chance to visit the newer website lenuage.io.

**Comment by bgaultier** [comment]
Done 👇
![Capture d’écran 2020-11-07 à 15 49 45](https://user-images.githubusercontent.com/177940/98444266-fe9fa200-2110-11eb-8215-7d14706b72ac.png)

https://www.laboite.cc/

**Comment by jlebunetel** [comment]
:thumbsup:
